[colors.primary]
background = "#0e0e16"
foreground = "#cdd6f4"

[colors.cursor]
text = "#0e0e16"
cursor = "#cdd6f4"

[colors.vi_mode_cursor]
text = "#0e0e16"
cursor = "#cdd6f4"

[colors.search.matches]
foreground = "#0e0e16"
background = "#cdd6f4"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#b8c0e0"
background = "#181926"

[colors.selection]
text = "CellBackground"
background = "#c6a0f6"

[colors.normal]
black = "#181926"
red = "#ed8796"
green = "#a6da95"
yellow = "#eed49f"
blue = "#8aadf4"
magenta = "#c6a0f6"
cyan = "#8bd5ca"
white = "#b8c0e0"

[colors.bright]
black = "#6e738d"
red = "#ed8796"
green = "#a6da95"
yellow = "#eed49f"
blue = "#8aadf4"
magenta = "#c6a0f6"
cyan = "#8bd5ca"
white = "#cad3f5"

[colors.dim]
black = "#181926"
red = "#ed8796"
green = "#a6da95"
yellow = "#eed49f"
blue = "#8aadf4"
magenta = "#c6a0f6"
cyan = "#8bd5ca"
white = "#b8c0e0"
