# Background and foreground colors
background = #0e0e16
foreground = #cdd6f4

# Standard colors
palette = 0=#0e0e16
palette = 1=#2a2a3b
palette = 2=#353748
palette = 3=#414356
palette = 4=#4d4f63
palette = 5=#585b70
palette = 6=#64687d
palette = 7=#70748a

# Bright colors
palette = 8=#7b8098
palette = 9=#878ca5
palette = 10=#9399b2
palette = 11=#9ea5bf
palette = 12=#aab1cc
palette = 13=#b6bdda
palette = 14=#c1cae7
palette = 15=#cdd6f4
