# Background and foreground colors
background = #0e0e16
foreground = #cdd6f4

# Standard colors
palette = 0=#181926
palette = 1=#ed8796
palette = 2=#a6da95
palette = 3=#eed49f
palette = 4=#8aadf4
palette = 5=#c6a0f6
palette = 6=#8bd5ca
palette = 7=#b8c0e0

# Bright colors
palette = 8=#6e738d
palette = 9=#ed8796
palette = 10=#a6da95
palette = 11=#eed49f
palette = 12=#8aadf4
palette = 13=#c6a0f6
palette = 14=#8bd5ca
palette = 15=#cad3f5
