background            #0e0e16
foreground            #cdd6f4

# black
color0  #0e0e16
color8  #7b8098

# red
color1  #2a2a3b
color9  #878ca5

# green
color2  #353748
color10 #9399b2

# yellow
color3  #414356
color11 #9ea5bf

# blue
color4  #4d4f63
color12 #aab1cc

# magenta
color5  #585b70
color13 #b6bdda

#cyan
color6  #64687d
color14 #c1cae7

#white
color7  #70748a
color15 #cdd6f4


